import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./styles/GlobalStyles.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "핸드폰으로 랜선여행",
  description: "Generated by create lhyjjg",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
